name: easy_work
description: "ແອັບຈັດການວຽກງານສຳລັບອົງກອນ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase (ไม่ใช้ storage)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  # firebase_storage: ^12.3.2  # ปิดไว้
  
  # State Management
  provider: ^6.1.2
  
  # UI & Navigation
  go_router: ^14.6.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  
  # UI Components
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/